#! /usr/bin/env python

import sys
from nagios_cli.cli import CLI
from nagios_cli.config import Config

def run():
    import optparse

    parser = optparse.OptionParser(usage='%prog [<options>] [<host> [<service>]]')
    parser.add_option('-c', '--config',
        help='Configuration file')

    options, args = parser.parse_args()

    config = Config()
    config.load_default()
    if options.config:
        config.load(options.config)

    cli = CLI(config)
    return cli.run()

if __name__ == '__main__':
    sys.exit(run())

